### ISSUE TITLE
Show a modal before deleting an item

### ISSUE THREAD

**Issue by EslemOuederni** [EslemOuederni/transportation-app-dashboard#6]
Before you delete something from the tickets/ trips or transportation mean table, you have to confirm with a pop up modal that you can find in clients/components/modal.jsx .

**Comment by vOid9201** [comment]
Mam i was looking to solve the issue , but before when i was trying to run the "npm run-script client" then it shows  missing script client

**Comment by EslemOuederni** [comment]
Just do `cd client` -> `npm run dev` in the terminal.
Make sure to check the installation details. If you face any other problems, please let me know. Thank you!

**Comment by vOid9201** [comment]
I did the same but nothing is appearing on the screen , main.jsx file is not able to load the other react components from it

**Comment by EslemOuederni** [comment]
Oh I think I know what you mean. So basically the localhost is returning nothing, that's because I'm setting different endpoints. you can check the different end points in App.jsx where I have the different routes. so `127.0.0.1:5173/auth/login`  will take you to the login page and `http://127.0.0.1:5173/auth/register` for registering. For the dashboard home page go to `http://127.0.0.1:5173/dashboard/home`
I hope this fixes it !

**Comment by vOid9201** [comment]
ohh , thanks for helping , will try myy best to solve the issue

**Comment by EslemOuederni** [comment]
Thank you so much for helping out ! good luck

**Comment by gjuliao** [comment]
Hi @EslemOuederni is this issue covered? I might help you with it. Let me know.

**Comment by EslemOuederni** [comment]
> Hi @EslemOuederni is this issue covered? I might help you with it. Let me know.

Hey there, thank you for suggesting, I think this issue will be assigned to @vOid9201 but you can check the other [Issue](https://github.com/EslemOuederni/transportation-app-dashboard/issues/7#issue-1606578900) that is open

**Comment by EslemOuederni** [comment]
Reverted latest [pull request](https://github.com/EslemOuederni/transportation-app-dashboard/pull/9#issue-1611885359)
